from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166f046df20c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.alter_column('period_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('period_value',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('top_crop',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('top_location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.alter_column('crops_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('harvest', schema=None) as batch_op:
        batch_op.alter_column('farmer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('crop_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('farmer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'harvest'::text"))

    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('knowledge_comments', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('knowledge_likes', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('knowledge_likes_post_id_username_key'), type_='unique')

    with op.batch_alter_table('knowledge_posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('video',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'Published'::text"))
        batch_op.drop_constraint(batch_op.f('knowledge_posts_category_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('knowledge_replies', schema=None) as batch_op:
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('reply',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('buyer_username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('crop_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=True,
               existing_server_default=sa.text("'kg'::text"))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'available'::text"))
        batch_op.alter_column('order_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'available'::text"))
        batch_op.alter_column('listing_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('delivery_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('buyer_confirm_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('buyer_rating_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('marketplace_crop_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('marketplace_user_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('recipient',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_verified',sa.Boolean(),nullable=False,server_default=sa.false()))
        batch_op.add_column(sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'user'::text"))
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('reliability_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('reliability_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'Not Yet Rated'::text"))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('reliability_status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Not Yet Rated'::text"))
        batch_op.alter_column('reliability_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'user'::text"))
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('recipient',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sender',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('marketplace_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('marketplace_crop_id_fkey'), 'crops', ['crop_id'], ['id'])
        batch_op.alter_column('buyer_rating_date',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('buyer_confirm_date',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('delivery_date',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('listing_date',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('order_status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'available'::text"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'available'::text"))
        batch_op.alter_column('unit',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'kg'::text"))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('crop_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('buyer_username',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('knowledge_replies', schema=None) as batch_op:
        batch_op.alter_column('reply',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('knowledge_posts', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('knowledge_posts_category_id_fkey'), 'knowledge_categories', ['category_id'], ['category_id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Published'::text"))
        batch_op.alter_column('video',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('knowledge_likes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('knowledge_likes_post_id_username_key'), ['post_id', 'username'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('knowledge_comments', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'harvest'::text"))
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('farmer',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('crop_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('harvest', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_received',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('farmer',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.alter_column('crops_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.alter_column('top_location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('top_crop',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('period_value',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('period_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
