"""Add member models

Revision ID: fd6d67b9de23
Revises: 166f046df20c
Create Date: 2026-08-26 22:57:54.210094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6d67b9de23'
down_revision = '166f046df20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.drop_column('main_image')

    op.drop_table('marketplace_images')
    op.drop_table('cart')
    # ### end Alembic commands ###
